export const regions = [
  // England (30)
  "Bedfordshire",
  "Berkshire",
  "Bristol",
  "Buckinghamshire",
  "Cambridgeshire",
  "Cheshire",
  "Cornwall",
  "Cumbria",
  "Derbyshire",
  "Devon",
  "Dorset",
  "Durham",
  "East Sussex",
  "Essex",
  "Gloucestershire",
  "Greater London",
  "Greater Manchester",
  "Hampshire",
  "Herefordshire",
  "Hertfordshire",
  "Kent",
  "Lancashire",
  "Leicestershire",
  "Lincolnshire",
  "Merseyside",
  "Norfolk",
  "North Yorkshire",
  "Northamptonshire",
  "Northumberland",
  "Nottinghamshire",

  // Scotland (10)
  "Aberdeenshire",
  "Angus",
  "Fife",
  "Highland",
  "Midlothian",
  "Renfrewshire",
  "Scottish Borders",
  "South Lanarkshire",
  "West Lothian",
  "Shetland Islands",

  // Wales (5)
  "Anglesey",
  "Cardiff",
  "Carmarthenshire",
  "Gwynedd",
  "Swansea",

  // Northern Ireland (5)
  "Antrim",
  "Armagh",
  "Down",
  "Fermanagh",
  "Londonderry",
];
